services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\DataFixtures\:
        resource: '%kernel.project_dir%/tests/DataFixtures/'
        tags: [doctrine.fixture.orm]
