version: '3.9'

networks:
    default:
        external: true
        name: ${NETWORK_NAME}

services:
    gotify:
       container_name: ${GOTIFY_CONTAINER_NAME}
       image: gotify/server
       environment:
           GOTIFY_SERVER_PORT: 80
           GOTIFY_DATABASE_DIALECT: sqlite3
           GOTIFY_DATABASE_CONNECTION: data/gotify.db
           GOTIFY_DEFAULTUSER_NAME: admin
           GOTIFY_DEFAULTUSER_PASS: admin
           GOTIFY_REGISTRATION: true
       labels:
         - traefik.http.routers.${GOTIFY_CONTAINER_NAME}.rule=Host(`${GOTIFY_CONTAINER_HOSTNAME}`)
         - traefik.http.routers.${GOTIFY_CONTAINER_NAME}.service=${GOTIFY_CONTAINER_NAME}
         - traefik.http.services.${GOTIFY_CONTAINER_NAME}.loadbalancer.server.port=80
       networks:
         - default
       profiles:
         - gotify
