version: "3.9"

networks:
    default:
        external: true
        name: ${NETWORK_NAME}

services:
    traefik:
        image: traefik:latest
        container_name: ${TRAEFIK_CONTAINER_NAME}
#        command: --api --docker
        networks:
            - default
        ports:
            - ${WEB_APP_PORT}:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../../traefik/traefik.yml:/traefik.yml:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=${NETWORK_NAME}
            - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}.rule=Host(`${TRAEFIK_CONTAINER_HOSTNAME}`)
            - traefik.http.routers.${TRAEFIK_CONTAINER_NAME}.service=api@internal
        profiles:
            - traefik